server:
  port: 8060
spring:
  application:
    name: hystrix
eureka:
  client:
    service-url:
      defaultZone:  http://user:123456@eureka000.com:8761/eureka/,http://user:123456@eureka001.com:8761/eureka/,http://user:123456@eureka002.com:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
#断路器，起到降级作用，避免服务雪崩
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'
hystrix:
  dashboard:
    proxy-stream-allow-list: localhost
