spring:
 application:
  name: consumer-dept

server:
 port: 80

#Eureka的配置，该服务注册到eureka的地址
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka
 instance:
  #修改Eureka监控页中status的默认描述信息。不配置默认为DESKTOP-XXX描述
  instance-id: springcloud-consumer-dept-80


 #热部署
devtools:
  restart:
   #热部署生效
   enabled: true
    #设置重启目录
    additional-paths: src/main/java
    #classpath目录下的WEB-INF文件夹内容修改不重启
    exclude: WEB-INF/**
