server:
  port: 9001
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
      -   id: routes-dept-server
          uri: lb://provider
          predicates:
          - Path=/dept/**

      -   id: routes-user-server
          uri: lb://provider
          predicates:
          - Path=/user/**
    discovery:
      locator:
        enabled: true # 开启从注册中心动态创建路由的功能
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,localhost:8763/eureka
  instance:
    instance-id: gateway-server
    prefer-ip-address: true