spring:
  application:
    name: serviceA

message: '{cipher}AQBUJqUaIrn6FyMrokiLAD6vfNQddXNMfYFTnCttQa1mL5Hfp9zRXgFLurfX6MX6uo8+3WnioaxmQ9iBEkruVwCU1uxn/UAAh5TROfQ91GKvqevuPXyzLdfr7v5i9BZ8lP8mgl1WIfEwkcLODYV+bfIMNbTDf7+Nqu1In+ZemsLyfJmFzQz7PzmbjJ1MmS/vDrQ1EOOFvDj+CpCaaR26yud2Zr5KVmCFiF9BYqksRZi6wTYcd4x7TkZehlS4shceLFRfBowvgTOZ6O8NKipnW0Hah64lWHZYxL1+4kWRwJDMNSrLk8qVuL11yJRFOGfgqgiTqE7HfUD8k0iU3OEkmlFAxDbNfeR6VJKw4qhdJ2UJUG04+BdRkFgC2J1KiLW5eLE='
