spring:
  application:
    name: serviceA

#Eureka的配置，该服务注册到eureka的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://test:123456@localhost:8761/eureka,http://test:123456@localhost:8762/eureka,http://test:123456@localhost:8763/eureka


message: "远程配置11"
