spring:
  application:
    name: serviceA

message: {cipher}AQAUsPxquYJWhfvklbW8GRLKfoPIatZ/jBvGivHdQkkFvZVErsWdwBjeQauizd2oFn3QlD6ENW8Zoq84bdEEK4BF5mc0dPk1Vk+RoQpJzmqgrDm3/lFMxGezeZM4VK2GwBtw+cTRuoe3GlLW+PtPs3muoTw4UvtTgDek353SyIT1kZAxLsWwg49B+ZacWimFlPl46zAfkYKAfNTdE9Ho7+7dcSC3/TF8VLlSr9FGaTb5QJHc00StjhZWcaFSrNFe1YNvm/EL7Hzg97G6afi+9ePjyLGx9OM6nHjOBs9sLETj7/dmXPgRxp0pa58ELpVxlfBKonBnfprzYrud5PMa+yR3hXOTT7DyFgb2v9H5xYiaU+cClThdJxbj8VHcbFGkD/YSb8EOGsmoJ/K8DBGI0xyh
