server:
  port: 8020

spring:
  application:
    name: serviceAAAAAAAb

#Eureka的配置，该服务注册到eureka的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
