spring:
  application:
    name: serviceA
message: {cipher}AQC/gg8fwcTvELWElYYcFCJzYEHL02QxfFFrMvVe0pbYdy4loJ7lk3fIRgi3+s9z8wcUTFkLlBr/Amc7V2eWDnhMG1FIgLKGh4yK9ZShYfLEF9GFAIc4x5l9YxCblXIXj+XBob4X+A23S6rcdsaAISwCPcIhq5GbE0rRpdD9e6jaBVihvt/ySc9YoFBWrxOtAd/SD66s5D/ZfrYMUS5M9mSTkwIMVEk/AWt2xGOj0COGjQkQBT/GojaTxd/29c/n8YkhjcJ+j88g9c1W32IzFLqSbt9zjPwiPViAmemMHq4Jv3aLbD1IiwdPFiDD8i/JjJYUJ8v36kFPAx9S9sRtCpYt+3pu3JS6N9Uvpjazo3GBUDv+RQosYSu165Hj4nSoxjY=
