server:
  port: 8080

spring:
  application:
    name: springsecurity + jwt
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: 852717
  mvc:
    static-path-pattern: /templates/**
  thymeleaf:
    cache: false

jwt:
  secret: q3t6w9z$C&F)J@NcQfTjWnZr4u7xqwerasfdddffvssssghcerhfvf #这里可以自己定制
  expire: 3600000 # 过期时间,单位毫秒
  header: testProject #随意定制


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springcloud.entity
  config-location: classpath:mybatis/mybatis-config.xml

#showSql
logging:
  level:
    com:
      example:
        springcloud:
          mapper: debug
          controller: info
