server:
  port: 8003
spring:
  application:
    name: provider
  datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: 852717

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml

#showSql
logging:
  level:
    com:
      example:
        springcloud:
          mapper: debug
          controller: info


#Eureka的配置，该服务注册到eureka的地址
eureka:
 client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
 instance:
     #修改Eureka监控页中status的默认描述信息。不配置默认为DESKTOP-XXX描述
    instance-id: springcloud-provider-dept-8003
   # 心跳检测检测与续约时间
   # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

#热部署
devtools:
  restart:
    enabled: true
    ditional-paths: src/main/java
    exclude: WEB/INF/**